name: Build

on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 10 * * 1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      name: Setup Node
      with:
        node-version: '10.x'
    - name: Install Dependencies
      run: |
        npm i
    - name: Build
      run: |
        npm run build

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      name: Setup Node
      with:
        node-version: '10.x'
    - name: Install Dependencies
      run: |
        npm i
    - name: Run Tests
      run: |
        CI=true npm run test
